# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Nexys4DdrSpectralSources/src/ip/xfft_1/xfft_1.xci
# IP: The module: 'xfft_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Nexys4DdrSpectralSources/src/ip/xfft_1/xfft_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Nexys4DdrSpectralSources/src/ip/xfft_1/xfft_1.xci
# IP: The module: 'xfft_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Nexys4DdrSpectralSources/src/ip/xfft_1/xfft_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
